#[derive(Debug, PartialEq, Eq, Clone)]
pub struct Music {
    pub sounds: Vec<Sound>,
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub struct Sheet {
    pub lines: Vec<Line>,
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub enum Line {
    Symbol(Symbol),
    Sound(Sound),
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub enum Symbol {
    Label(String),
    Dal(String),
    DalAlFine(String),
    DaCapo,
    DaCapoAlFine,
    Fine,
    SRepeat,
    ERepeat,
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub struct Sound {
    pub chord: Vec<Note>,
    pub duration: Duration,
    pub volume: Volume,
}

#[derive(Debug, PartialEq, Eq, Clone)]
pub enum Note {
    C0,
    Cs0,
    Df0,
    D0,
    Ds0,
    Ef0,
    E0,
    F0,
    Fs0,
    Gf0,
    G0,
    Gs0,
    Af0,
    A0,
    As0,
    Bf0,
    B0,
    C1,
    Cs1,
    Df1,
    D1,
    Ds1,
    Ef1,
    E1,
    F1,
    Fs1,
    Gf1,
    G1,
    Gs1,
    Af1,
    A1,
    As1,
    Bf1,
    B1,
    C2,
    Cs2,
    Df2,
    D2,
    Ds2,
    Ef2,
    E2,
    F2,
    Fs2,
    Gf2,
    G2,
    Gs2,
    Af2,
    A2,
    As2,
    Bf2,
    B2,
    C3,
    Cs3,
    Df3,
    D3,
    Ds3,
    Ef3,
    E3,
    F3,
    Fs3,
    Gf3,
    G3,
    Gs3,
    Af3,
    A3,
    As3,
    Bf3,
    B3,
    C4,
    Cs4,
    Df4,
    D4,
    Ds4,
    Ef4,
    E4,
    F4,
    Fs4,
    Gf4,
    G4,
    Gs4,
    Af4,
    A4,
    As4,
    Bf4,
    B4,
    C5,
    Cs5,
    Df5,
    D5,
    Ds5,
    Ef5,
    E5,
    F5,
    Fs5,
    Gf5,
    G5,
    Gs5,
    Af5,
    A5,
    As5,
    Bf5,
    B5,
    C6,
    Cs6,
    Df6,
    D6,
    Ds6,
    Ef6,
    E6,
    F6,
    Fs6,
    Gf6,
    G6,
    Gs6,
    Af6,
    A6,
    As6,
    Bf6,
    B6,
    C7,
    Cs7,
    Df7,
    D7,
    Ds7,
    Ef7,
    E7,
    F7,
    Fs7,
    Gf7,
    G7,
    Gs7,
    Af7,
    A7,
    As7,
    Bf7,
    B7,
    C8,
}

pub type Duration = u32;
pub type Hertz = u16;
pub type Volume = u8;

impl Note {
    pub fn from(note: &str) -> Option<Self> {
        match note {
            "C0" => Some(Self::C0),
            "Cs0" => Some(Self::Cs0),
            "Df0" => Some(Self::Df0),
            "D0" => Some(Self::D0),
            "Ds0" => Some(Self::Ds0),
            "Ef0" => Some(Self::Ef0),
            "E0" => Some(Self::E0),
            "F0" => Some(Self::F0),
            "Fs0" => Some(Self::Fs0),
            "Gf0" => Some(Self::Gf0),
            "G0" => Some(Self::G0),
            "Gs0" => Some(Self::Gs0),
            "Af0" => Some(Self::Af0),
            "A0" => Some(Self::A0),
            "As0" => Some(Self::As0),
            "Bf0" => Some(Self::Bf0),
            "B0" => Some(Self::B0),
            "C1" => Some(Self::C1),
            "Cs1" => Some(Self::Cs1),
            "Df1" => Some(Self::Df1),
            "D1" => Some(Self::D1),
            "Ds1" => Some(Self::Ds1),
            "Ef1" => Some(Self::Ef1),
            "E1" => Some(Self::E1),
            "F1" => Some(Self::F1),
            "Fs1" => Some(Self::Fs1),
            "Gf1" => Some(Self::Gf1),
            "G1" => Some(Self::G1),
            "Gs1" => Some(Self::Gs1),
            "Af1" => Some(Self::Af1),
            "A1" => Some(Self::A1),
            "As1" => Some(Self::As1),
            "Bf1" => Some(Self::Bf1),
            "B1" => Some(Self::B1),
            "C2" => Some(Self::C2),
            "Cs2" => Some(Self::Cs2),
            "Df2" => Some(Self::Df2),
            "D2" => Some(Self::D2),
            "Ds2" => Some(Self::Ds2),
            "Ef2" => Some(Self::Ef2),
            "E2" => Some(Self::E2),
            "F2" => Some(Self::F2),
            "Fs2" => Some(Self::Fs2),
            "Gf2" => Some(Self::Gf2),
            "G2" => Some(Self::G2),
            "Gs2" => Some(Self::Gs2),
            "Af2" => Some(Self::Af2),
            "A2" => Some(Self::A2),
            "As2" => Some(Self::As2),
            "Bf2" => Some(Self::Bf2),
            "B2" => Some(Self::B2),
            "C3" => Some(Self::C3),
            "Cs3" => Some(Self::Cs3),
            "Df3" => Some(Self::Df3),
            "D3" => Some(Self::D3),
            "Ds3" => Some(Self::Ds3),
            "Ef3" => Some(Self::Ef3),
            "E3" => Some(Self::E3),
            "F3" => Some(Self::F3),
            "Fs3" => Some(Self::Fs3),
            "Gf3" => Some(Self::Gf3),
            "G3" => Some(Self::G3),
            "Gs3" => Some(Self::Gs3),
            "Af3" => Some(Self::Af3),
            "A3" => Some(Self::A3),
            "As3" => Some(Self::As3),
            "Bf3" => Some(Self::Bf3),
            "B3" => Some(Self::B3),
            "C4" => Some(Self::C4),
            "Cs4" => Some(Self::Cs4),
            "Df4" => Some(Self::Df4),
            "D4" => Some(Self::D4),
            "Ds4" => Some(Self::Ds4),
            "Ef4" => Some(Self::Ef4),
            "E4" => Some(Self::E4),
            "F4" => Some(Self::F4),
            "Fs4" => Some(Self::Fs4),
            "Gf4" => Some(Self::Gf4),
            "G4" => Some(Self::G4),
            "Gs4" => Some(Self::Gs4),
            "Af4" => Some(Self::Af4),
            "A4" => Some(Self::A4),
            "As4" => Some(Self::As4),
            "Bf4" => Some(Self::Bf4),
            "B4" => Some(Self::B4),
            "C5" => Some(Self::C5),
            "Cs5" => Some(Self::Cs5),
            "Df5" => Some(Self::Df5),
            "D5" => Some(Self::D5),
            "Ds5" => Some(Self::Ds5),
            "Ef5" => Some(Self::Ef5),
            "E5" => Some(Self::E5),
            "F5" => Some(Self::F5),
            "Fs5" => Some(Self::Fs5),
            "Gf5" => Some(Self::Gf5),
            "G5" => Some(Self::G5),
            "Gs5" => Some(Self::Gs5),
            "Af5" => Some(Self::Af5),
            "A5" => Some(Self::A5),
            "As5" => Some(Self::As5),
            "Bf5" => Some(Self::Bf5),
            "B5" => Some(Self::B5),
            "C6" => Some(Self::C6),
            "Cs6" => Some(Self::Cs6),
            "Df6" => Some(Self::Df6),
            "D6" => Some(Self::D6),
            "Ds6" => Some(Self::Ds6),
            "Ef6" => Some(Self::Ef6),
            "E6" => Some(Self::E6),
            "F6" => Some(Self::F6),
            "Fs6" => Some(Self::Fs6),
            "Gf6" => Some(Self::Gf6),
            "G6" => Some(Self::G6),
            "Gs6" => Some(Self::Gs6),
            "Af6" => Some(Self::Af6),
            "A6" => Some(Self::A6),
            "As6" => Some(Self::As6),
            "Bf6" => Some(Self::Bf6),
            "B6" => Some(Self::B6),
            "C7" => Some(Self::C7),
            "Cs7" => Some(Self::Cs7),
            "Df7" => Some(Self::Df7),
            "D7" => Some(Self::D7),
            "Ds7" => Some(Self::Ds7),
            "Ef7" => Some(Self::Ef7),
            "E7" => Some(Self::E7),
            "F7" => Some(Self::F7),
            "Fs7" => Some(Self::Fs7),
            "Gf7" => Some(Self::Gf7),
            "G7" => Some(Self::G7),
            "Gs7" => Some(Self::Gs7),
            "Af7" => Some(Self::Af7),
            "A7" => Some(Self::A7),
            "As7" => Some(Self::As7),
            "Bf7" => Some(Self::Bf7),
            "B7" => Some(Self::B7),
            "C8" => Some(Self::C8),
            _ => None,
        }
    }
}
